### ISSUE TITLE
complete circle as menu options

### ISSUE THREAD

**Issue by machelix** [Yeekyo/TYCircleMenu#1]
Hi Yeekyo

Thanks for the library. I have one question. is it possible to create collectionview on the complete circle instead of section of the circle? I would like to use wheel in one of my project and want complete circle having options instead of one fourth section.  

Thanks in advance.

**Comment by Yeekyo** [comment]
Do you mean to make the complete circle showing ,you don't need to use collectionView
https://github.com/funkyboy/How-To-Create-a-Rotating-Wheel-Control-with-UIKit
this library may help you!
I have add the loop feature to the version 1.1,thank you for your issues

**Comment by machelix** [comment]
Thanks for your reply. do you have perspective date for version 1.1 release?
